FROM node:10-alpine

WORKDIR /app
COPY package*.json /app/
COPY . .
RUN apk --no-cache --virtual build-dependencies add \
    krb5-dev \
    python \
    make \
    g++ \
    && npm install --silent \
    && apk del build-dependencies \
    && npm run build
CMD ["npm", "run", "start"]
EXPOSE 3030
